language: objective-c
osx_image: xcode9
branches:
  only:
    - master
env:
  - IOS_VERSION="11.0" DEVICE_NAME="iPhone 7"
  - PROJECT=ABNSDemo.xcodeproj
  - SCHEME="ABNSDemo"
before_install:
    - gem install xcpretty -N
script:
    travis_retry xcodebuild build-for-testing -project "$PROJECT" -scheme "$SCHEME" -sdk iphonesimulator11.0 -destination "platform=iOS Simulator,name=$DEVICE_NAME,OS=$IOS_VERSION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
